// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample/src/main/java/com/javalive09/sample/protoc/Json_Proto.proto

package com.javalive09.sample.protoc;

public final class JsonToProto {
  private JsonToProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sample.VideoBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vid = 1;</code>
     */
    java.lang.String getVid();
    /**
     * <code>string vid = 1;</code>
     */
    com.google.protobuf.ByteString
        getVidBytes();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string pic = 3;</code>
     */
    java.lang.String getPic();
    /**
     * <code>string pic = 3;</code>
     */
    com.google.protobuf.ByteString
        getPicBytes();

    /**
     * <code>int32 pay_type = 4;</code>
     */
    int getPayType();
  }
  /**
   * Protobuf type {@code sample.VideoBean}
   */
  public  static final class VideoBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sample.VideoBean)
      VideoBeanOrBuilder {
    // Use VideoBean.newBuilder() to construct.
    private VideoBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoBean() {
      vid_ = "";
      title_ = "";
      pic_ = "";
      payType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VideoBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              vid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              pic_ = s;
              break;
            }
            case 32: {

              payType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.javalive09.sample.protoc.JsonToProto.internal_static_sample_VideoBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.javalive09.sample.protoc.JsonToProto.internal_static_sample_VideoBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.javalive09.sample.protoc.JsonToProto.VideoBean.class, com.javalive09.sample.protoc.JsonToProto.VideoBean.Builder.class);
    }

    public static final int VID_FIELD_NUMBER = 1;
    private volatile java.lang.Object vid_;
    /**
     * <code>string vid = 1;</code>
     */
    public java.lang.String getVid() {
      java.lang.Object ref = vid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vid_ = s;
        return s;
      }
    }
    /**
     * <code>string vid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVidBytes() {
      java.lang.Object ref = vid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object pic_;
    /**
     * <code>string pic = 3;</code>
     */
    public java.lang.String getPic() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pic_ = s;
        return s;
      }
    }
    /**
     * <code>string pic = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPicBytes() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAY_TYPE_FIELD_NUMBER = 4;
    private int payType_;
    /**
     * <code>int32 pay_type = 4;</code>
     */
    public int getPayType() {
      return payType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vid_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getPicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pic_);
      }
      if (payType_ != 0) {
        output.writeInt32(4, payType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vid_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getPicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pic_);
      }
      if (payType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, payType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.javalive09.sample.protoc.JsonToProto.VideoBean)) {
        return super.equals(obj);
      }
      com.javalive09.sample.protoc.JsonToProto.VideoBean other = (com.javalive09.sample.protoc.JsonToProto.VideoBean) obj;

      boolean result = true;
      result = result && getVid()
          .equals(other.getVid());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getPic()
          .equals(other.getPic());
      result = result && (getPayType()
          == other.getPayType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VID_FIELD_NUMBER;
      hash = (53 * hash) + getVid().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + PIC_FIELD_NUMBER;
      hash = (53 * hash) + getPic().hashCode();
      hash = (37 * hash) + PAY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPayType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.JsonToProto.VideoBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.javalive09.sample.protoc.JsonToProto.VideoBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sample.VideoBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sample.VideoBean)
        com.javalive09.sample.protoc.JsonToProto.VideoBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.javalive09.sample.protoc.JsonToProto.internal_static_sample_VideoBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.javalive09.sample.protoc.JsonToProto.internal_static_sample_VideoBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.javalive09.sample.protoc.JsonToProto.VideoBean.class, com.javalive09.sample.protoc.JsonToProto.VideoBean.Builder.class);
      }

      // Construct using com.javalive09.sample.protoc.JsonToProto.VideoBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        vid_ = "";

        title_ = "";

        pic_ = "";

        payType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.javalive09.sample.protoc.JsonToProto.internal_static_sample_VideoBean_descriptor;
      }

      public com.javalive09.sample.protoc.JsonToProto.VideoBean getDefaultInstanceForType() {
        return com.javalive09.sample.protoc.JsonToProto.VideoBean.getDefaultInstance();
      }

      public com.javalive09.sample.protoc.JsonToProto.VideoBean build() {
        com.javalive09.sample.protoc.JsonToProto.VideoBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.javalive09.sample.protoc.JsonToProto.VideoBean buildPartial() {
        com.javalive09.sample.protoc.JsonToProto.VideoBean result = new com.javalive09.sample.protoc.JsonToProto.VideoBean(this);
        result.vid_ = vid_;
        result.title_ = title_;
        result.pic_ = pic_;
        result.payType_ = payType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.javalive09.sample.protoc.JsonToProto.VideoBean) {
          return mergeFrom((com.javalive09.sample.protoc.JsonToProto.VideoBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.javalive09.sample.protoc.JsonToProto.VideoBean other) {
        if (other == com.javalive09.sample.protoc.JsonToProto.VideoBean.getDefaultInstance()) return this;
        if (!other.getVid().isEmpty()) {
          vid_ = other.vid_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getPic().isEmpty()) {
          pic_ = other.pic_;
          onChanged();
        }
        if (other.getPayType() != 0) {
          setPayType(other.getPayType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.javalive09.sample.protoc.JsonToProto.VideoBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.javalive09.sample.protoc.JsonToProto.VideoBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object vid_ = "";
      /**
       * <code>string vid = 1;</code>
       */
      public java.lang.String getVid() {
        java.lang.Object ref = vid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVidBytes() {
        java.lang.Object ref = vid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vid = 1;</code>
       */
      public Builder setVid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vid = 1;</code>
       */
      public Builder clearVid() {
        
        vid_ = getDefaultInstance().getVid();
        onChanged();
        return this;
      }
      /**
       * <code>string vid = 1;</code>
       */
      public Builder setVidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pic_ = "";
      /**
       * <code>string pic = 3;</code>
       */
      public java.lang.String getPic() {
        java.lang.Object ref = pic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pic = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPicBytes() {
        java.lang.Object ref = pic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pic = 3;</code>
       */
      public Builder setPic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pic = 3;</code>
       */
      public Builder clearPic() {
        
        pic_ = getDefaultInstance().getPic();
        onChanged();
        return this;
      }
      /**
       * <code>string pic = 3;</code>
       */
      public Builder setPicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pic_ = value;
        onChanged();
        return this;
      }

      private int payType_ ;
      /**
       * <code>int32 pay_type = 4;</code>
       */
      public int getPayType() {
        return payType_;
      }
      /**
       * <code>int32 pay_type = 4;</code>
       */
      public Builder setPayType(int value) {
        
        payType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pay_type = 4;</code>
       */
      public Builder clearPayType() {
        
        payType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sample.VideoBean)
    }

    // @@protoc_insertion_point(class_scope:sample.VideoBean)
    private static final com.javalive09.sample.protoc.JsonToProto.VideoBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.javalive09.sample.protoc.JsonToProto.VideoBean();
    }

    public static com.javalive09.sample.protoc.JsonToProto.VideoBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoBean>
        PARSER = new com.google.protobuf.AbstractParser<VideoBean>() {
      public VideoBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VideoBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VideoBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoBean> getParserForType() {
      return PARSER;
    }

    public com.javalive09.sample.protoc.JsonToProto.VideoBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_VideoBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_VideoBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBsample/src/main/java/com/javalive09/sa" +
      "mple/protoc/Json_Proto.proto\022\006sample\"F\n\t" +
      "VideoBean\022\013\n\003vid\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\013\n" +
      "\003pic\030\003 \001(\t\022\020\n\010pay_type\030\004 \001(\005B+\n\034com.java" +
      "live09.sample.protocB\013JsonToProtob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sample_VideoBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sample_VideoBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_VideoBean_descriptor,
        new java.lang.String[] { "Vid", "Title", "Pic", "PayType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
