// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample/src/main/java/com/javalive09/sample/protoc/VideoItem.proto

package com.javalive09.sample.protoc;

public final class VideoItem {
  private VideoItem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.javalive09.sample.protoc.VideoItem.ExtendInfo.info);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sample.VideoBean)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<VideoBean> {

    /**
     * <code>required string vid = 1;</code>
     */
    boolean hasVid();
    /**
     * <code>required string vid = 1;</code>
     */
    java.lang.String getVid();
    /**
     * <code>required string vid = 1;</code>
     */
    com.google.protobuf.ByteString
        getVidBytes();

    /**
     * <code>optional string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string pic = 3;</code>
     */
    boolean hasPic();
    /**
     * <code>optional string pic = 3;</code>
     */
    java.lang.String getPic();
    /**
     * <code>optional string pic = 3;</code>
     */
    com.google.protobuf.ByteString
        getPicBytes();

    /**
     * <code>optional int32 pay_type = 4;</code>
     */
    boolean hasPayType();
    /**
     * <code>optional int32 pay_type = 4;</code>
     */
    int getPayType();
  }
  /**
   * Protobuf type {@code sample.VideoBean}
   */
  public  static final class VideoBean extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        VideoBean> implements
      // @@protoc_insertion_point(message_implements:sample.VideoBean)
      VideoBeanOrBuilder {
    // Use VideoBean.newBuilder() to construct.
    private VideoBean(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<com.javalive09.sample.protoc.VideoItem.VideoBean, ?> builder) {
      super(builder);
    }
    private VideoBean() {
      vid_ = "";
      title_ = "";
      pic_ = "";
      payType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VideoBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              vid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              pic_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              payType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.javalive09.sample.protoc.VideoItem.internal_static_sample_VideoBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.javalive09.sample.protoc.VideoItem.internal_static_sample_VideoBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.javalive09.sample.protoc.VideoItem.VideoBean.class, com.javalive09.sample.protoc.VideoItem.VideoBean.Builder.class);
    }

    private int bitField0_;
    public static final int VID_FIELD_NUMBER = 1;
    private volatile java.lang.Object vid_;
    /**
     * <code>required string vid = 1;</code>
     */
    public boolean hasVid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string vid = 1;</code>
     */
    public java.lang.String getVid() {
      java.lang.Object ref = vid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string vid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVidBytes() {
      java.lang.Object ref = vid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object pic_;
    /**
     * <code>optional string pic = 3;</code>
     */
    public boolean hasPic() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string pic = 3;</code>
     */
    public java.lang.String getPic() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pic = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPicBytes() {
      java.lang.Object ref = pic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAY_TYPE_FIELD_NUMBER = 4;
    private int payType_;
    /**
     * <code>optional int32 pay_type = 4;</code>
     */
    public boolean hasPayType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 pay_type = 4;</code>
     */
    public int getPayType() {
      return payType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<com.javalive09.sample.protoc.VideoItem.VideoBean>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, payType_);
      }
      extensionWriter.writeUntil(201, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, payType_);
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.javalive09.sample.protoc.VideoItem.VideoBean)) {
        return super.equals(obj);
      }
      com.javalive09.sample.protoc.VideoItem.VideoBean other = (com.javalive09.sample.protoc.VideoItem.VideoBean) obj;

      boolean result = true;
      result = result && (hasVid() == other.hasVid());
      if (hasVid()) {
        result = result && getVid()
            .equals(other.getVid());
      }
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && getTitle()
            .equals(other.getTitle());
      }
      result = result && (hasPic() == other.hasPic());
      if (hasPic()) {
        result = result && getPic()
            .equals(other.getPic());
      }
      result = result && (hasPayType() == other.hasPayType());
      if (hasPayType()) {
        result = result && (getPayType()
            == other.getPayType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVid()) {
        hash = (37 * hash) + VID_FIELD_NUMBER;
        hash = (53 * hash) + getVid().hashCode();
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasPic()) {
        hash = (37 * hash) + PIC_FIELD_NUMBER;
        hash = (53 * hash) + getPic().hashCode();
      }
      if (hasPayType()) {
        hash = (37 * hash) + PAY_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPayType();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.VideoItem.VideoBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.javalive09.sample.protoc.VideoItem.VideoBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sample.VideoBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          com.javalive09.sample.protoc.VideoItem.VideoBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:sample.VideoBean)
        com.javalive09.sample.protoc.VideoItem.VideoBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.javalive09.sample.protoc.VideoItem.internal_static_sample_VideoBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.javalive09.sample.protoc.VideoItem.internal_static_sample_VideoBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.javalive09.sample.protoc.VideoItem.VideoBean.class, com.javalive09.sample.protoc.VideoItem.VideoBean.Builder.class);
      }

      // Construct using com.javalive09.sample.protoc.VideoItem.VideoBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        vid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pic_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        payType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.javalive09.sample.protoc.VideoItem.internal_static_sample_VideoBean_descriptor;
      }

      public com.javalive09.sample.protoc.VideoItem.VideoBean getDefaultInstanceForType() {
        return com.javalive09.sample.protoc.VideoItem.VideoBean.getDefaultInstance();
      }

      public com.javalive09.sample.protoc.VideoItem.VideoBean build() {
        com.javalive09.sample.protoc.VideoItem.VideoBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.javalive09.sample.protoc.VideoItem.VideoBean buildPartial() {
        com.javalive09.sample.protoc.VideoItem.VideoBean result = new com.javalive09.sample.protoc.VideoItem.VideoBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vid_ = vid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pic_ = pic_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.payType_ = payType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.javalive09.sample.protoc.VideoItem.VideoBean, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.javalive09.sample.protoc.VideoItem.VideoBean, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.javalive09.sample.protoc.VideoItem.VideoBean, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.javalive09.sample.protoc.VideoItem.VideoBean, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.javalive09.sample.protoc.VideoItem.VideoBean) {
          return mergeFrom((com.javalive09.sample.protoc.VideoItem.VideoBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.javalive09.sample.protoc.VideoItem.VideoBean other) {
        if (other == com.javalive09.sample.protoc.VideoItem.VideoBean.getDefaultInstance()) return this;
        if (other.hasVid()) {
          bitField0_ |= 0x00000001;
          vid_ = other.vid_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasPic()) {
          bitField0_ |= 0x00000004;
          pic_ = other.pic_;
          onChanged();
        }
        if (other.hasPayType()) {
          setPayType(other.getPayType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVid()) {
          return false;
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.javalive09.sample.protoc.VideoItem.VideoBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.javalive09.sample.protoc.VideoItem.VideoBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object vid_ = "";
      /**
       * <code>required string vid = 1;</code>
       */
      public boolean hasVid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string vid = 1;</code>
       */
      public java.lang.String getVid() {
        java.lang.Object ref = vid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string vid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVidBytes() {
        java.lang.Object ref = vid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string vid = 1;</code>
       */
      public Builder setVid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string vid = 1;</code>
       */
      public Builder clearVid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vid_ = getDefaultInstance().getVid();
        onChanged();
        return this;
      }
      /**
       * <code>required string vid = 1;</code>
       */
      public Builder setVidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pic_ = "";
      /**
       * <code>optional string pic = 3;</code>
       */
      public boolean hasPic() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string pic = 3;</code>
       */
      public java.lang.String getPic() {
        java.lang.Object ref = pic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pic = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPicBytes() {
        java.lang.Object ref = pic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pic = 3;</code>
       */
      public Builder setPic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pic = 3;</code>
       */
      public Builder clearPic() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pic_ = getDefaultInstance().getPic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pic = 3;</code>
       */
      public Builder setPicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pic_ = value;
        onChanged();
        return this;
      }

      private int payType_ ;
      /**
       * <code>optional int32 pay_type = 4;</code>
       */
      public boolean hasPayType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 pay_type = 4;</code>
       */
      public int getPayType() {
        return payType_;
      }
      /**
       * <code>optional int32 pay_type = 4;</code>
       */
      public Builder setPayType(int value) {
        bitField0_ |= 0x00000008;
        payType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pay_type = 4;</code>
       */
      public Builder clearPayType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sample.VideoBean)
    }

    // @@protoc_insertion_point(class_scope:sample.VideoBean)
    private static final com.javalive09.sample.protoc.VideoItem.VideoBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.javalive09.sample.protoc.VideoItem.VideoBean();
    }

    public static com.javalive09.sample.protoc.VideoItem.VideoBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VideoBean>
        PARSER = new com.google.protobuf.AbstractParser<VideoBean>() {
      public VideoBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VideoBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VideoBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoBean> getParserForType() {
      return PARSER;
    }

    public com.javalive09.sample.protoc.VideoItem.VideoBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExtendInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sample.ExtendInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string subTitle = 1;</code>
     */
    boolean hasSubTitle();
    /**
     * <code>optional string subTitle = 1;</code>
     */
    java.lang.String getSubTitle();
    /**
     * <code>optional string subTitle = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubTitleBytes();

    /**
     * <code>optional string des = 2;</code>
     */
    boolean hasDes();
    /**
     * <code>optional string des = 2;</code>
     */
    java.lang.String getDes();
    /**
     * <code>optional string des = 2;</code>
     */
    com.google.protobuf.ByteString
        getDesBytes();

    /**
     * <code>optional string other = 3;</code>
     */
    boolean hasOther();
    /**
     * <code>optional string other = 3;</code>
     */
    java.lang.String getOther();
    /**
     * <code>optional string other = 3;</code>
     */
    com.google.protobuf.ByteString
        getOtherBytes();
  }
  /**
   * <pre>
   * Video，加上一个info
   * </pre>
   *
   * Protobuf type {@code sample.ExtendInfo}
   */
  public  static final class ExtendInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sample.ExtendInfo)
      ExtendInfoOrBuilder {
    // Use ExtendInfo.newBuilder() to construct.
    private ExtendInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtendInfo() {
      subTitle_ = "";
      des_ = "";
      other_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExtendInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              subTitle_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              des_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              other_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.javalive09.sample.protoc.VideoItem.internal_static_sample_ExtendInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.javalive09.sample.protoc.VideoItem.internal_static_sample_ExtendInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.javalive09.sample.protoc.VideoItem.ExtendInfo.class, com.javalive09.sample.protoc.VideoItem.ExtendInfo.Builder.class);
    }

    private int bitField0_;
    public static final int SUBTITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object subTitle_;
    /**
     * <code>optional string subTitle = 1;</code>
     */
    public boolean hasSubTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string subTitle = 1;</code>
     */
    public java.lang.String getSubTitle() {
      java.lang.Object ref = subTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subTitle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubTitleBytes() {
      java.lang.Object ref = subTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DES_FIELD_NUMBER = 2;
    private volatile java.lang.Object des_;
    /**
     * <code>optional string des = 2;</code>
     */
    public boolean hasDes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string des = 2;</code>
     */
    public java.lang.String getDes() {
      java.lang.Object ref = des_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          des_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string des = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDesBytes() {
      java.lang.Object ref = des_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        des_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHER_FIELD_NUMBER = 3;
    private volatile java.lang.Object other_;
    /**
     * <code>optional string other = 3;</code>
     */
    public boolean hasOther() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string other = 3;</code>
     */
    public java.lang.String getOther() {
      java.lang.Object ref = other_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          other_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string other = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOtherBytes() {
      java.lang.Object ref = other_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        other_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subTitle_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, des_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, other_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subTitle_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, des_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, other_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.javalive09.sample.protoc.VideoItem.ExtendInfo)) {
        return super.equals(obj);
      }
      com.javalive09.sample.protoc.VideoItem.ExtendInfo other = (com.javalive09.sample.protoc.VideoItem.ExtendInfo) obj;

      boolean result = true;
      result = result && (hasSubTitle() == other.hasSubTitle());
      if (hasSubTitle()) {
        result = result && getSubTitle()
            .equals(other.getSubTitle());
      }
      result = result && (hasDes() == other.hasDes());
      if (hasDes()) {
        result = result && getDes()
            .equals(other.getDes());
      }
      result = result && (hasOther() == other.hasOther());
      if (hasOther()) {
        result = result && getOther()
            .equals(other.getOther());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSubTitle()) {
        hash = (37 * hash) + SUBTITLE_FIELD_NUMBER;
        hash = (53 * hash) + getSubTitle().hashCode();
      }
      if (hasDes()) {
        hash = (37 * hash) + DES_FIELD_NUMBER;
        hash = (53 * hash) + getDes().hashCode();
      }
      if (hasOther()) {
        hash = (37 * hash) + OTHER_FIELD_NUMBER;
        hash = (53 * hash) + getOther().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.javalive09.sample.protoc.VideoItem.ExtendInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Video，加上一个info
     * </pre>
     *
     * Protobuf type {@code sample.ExtendInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sample.ExtendInfo)
        com.javalive09.sample.protoc.VideoItem.ExtendInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.javalive09.sample.protoc.VideoItem.internal_static_sample_ExtendInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.javalive09.sample.protoc.VideoItem.internal_static_sample_ExtendInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.javalive09.sample.protoc.VideoItem.ExtendInfo.class, com.javalive09.sample.protoc.VideoItem.ExtendInfo.Builder.class);
      }

      // Construct using com.javalive09.sample.protoc.VideoItem.ExtendInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        subTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        des_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        other_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.javalive09.sample.protoc.VideoItem.internal_static_sample_ExtendInfo_descriptor;
      }

      public com.javalive09.sample.protoc.VideoItem.ExtendInfo getDefaultInstanceForType() {
        return com.javalive09.sample.protoc.VideoItem.ExtendInfo.getDefaultInstance();
      }

      public com.javalive09.sample.protoc.VideoItem.ExtendInfo build() {
        com.javalive09.sample.protoc.VideoItem.ExtendInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.javalive09.sample.protoc.VideoItem.ExtendInfo buildPartial() {
        com.javalive09.sample.protoc.VideoItem.ExtendInfo result = new com.javalive09.sample.protoc.VideoItem.ExtendInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.subTitle_ = subTitle_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.des_ = des_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.other_ = other_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.javalive09.sample.protoc.VideoItem.ExtendInfo) {
          return mergeFrom((com.javalive09.sample.protoc.VideoItem.ExtendInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.javalive09.sample.protoc.VideoItem.ExtendInfo other) {
        if (other == com.javalive09.sample.protoc.VideoItem.ExtendInfo.getDefaultInstance()) return this;
        if (other.hasSubTitle()) {
          bitField0_ |= 0x00000001;
          subTitle_ = other.subTitle_;
          onChanged();
        }
        if (other.hasDes()) {
          bitField0_ |= 0x00000002;
          des_ = other.des_;
          onChanged();
        }
        if (other.hasOther()) {
          bitField0_ |= 0x00000004;
          other_ = other.other_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.javalive09.sample.protoc.VideoItem.ExtendInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.javalive09.sample.protoc.VideoItem.ExtendInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object subTitle_ = "";
      /**
       * <code>optional string subTitle = 1;</code>
       */
      public boolean hasSubTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string subTitle = 1;</code>
       */
      public java.lang.String getSubTitle() {
        java.lang.Object ref = subTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            subTitle_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subTitle = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubTitleBytes() {
        java.lang.Object ref = subTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subTitle = 1;</code>
       */
      public Builder setSubTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        subTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subTitle = 1;</code>
       */
      public Builder clearSubTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        subTitle_ = getDefaultInstance().getSubTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subTitle = 1;</code>
       */
      public Builder setSubTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        subTitle_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object des_ = "";
      /**
       * <code>optional string des = 2;</code>
       */
      public boolean hasDes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string des = 2;</code>
       */
      public java.lang.String getDes() {
        java.lang.Object ref = des_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            des_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string des = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDesBytes() {
        java.lang.Object ref = des_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          des_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string des = 2;</code>
       */
      public Builder setDes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        des_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string des = 2;</code>
       */
      public Builder clearDes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        des_ = getDefaultInstance().getDes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string des = 2;</code>
       */
      public Builder setDesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        des_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object other_ = "";
      /**
       * <code>optional string other = 3;</code>
       */
      public boolean hasOther() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string other = 3;</code>
       */
      public java.lang.String getOther() {
        java.lang.Object ref = other_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            other_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string other = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOtherBytes() {
        java.lang.Object ref = other_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          other_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string other = 3;</code>
       */
      public Builder setOther(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        other_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string other = 3;</code>
       */
      public Builder clearOther() {
        bitField0_ = (bitField0_ & ~0x00000004);
        other_ = getDefaultInstance().getOther();
        onChanged();
        return this;
      }
      /**
       * <code>optional string other = 3;</code>
       */
      public Builder setOtherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        other_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sample.ExtendInfo)
    }

    // @@protoc_insertion_point(class_scope:sample.ExtendInfo)
    private static final com.javalive09.sample.protoc.VideoItem.ExtendInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.javalive09.sample.protoc.VideoItem.ExtendInfo();
    }

    public static com.javalive09.sample.protoc.VideoItem.ExtendInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ExtendInfo>
        PARSER = new com.google.protobuf.AbstractParser<ExtendInfo>() {
      public ExtendInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ExtendInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExtendInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtendInfo> getParserForType() {
      return PARSER;
    }

    public com.javalive09.sample.protoc.VideoItem.ExtendInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int INFO_FIELD_NUMBER = 100;
    /**
     * <code>extend .sample.VideoBean { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.javalive09.sample.protoc.VideoItem.VideoBean,
        com.javalive09.sample.protoc.VideoItem.ExtendInfo> info = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.javalive09.sample.protoc.VideoItem.ExtendInfo.getDefaultInstance(),
          0,
          com.javalive09.sample.protoc.VideoItem.ExtendInfo.class,
          com.javalive09.sample.protoc.VideoItem.ExtendInfo.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_VideoBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_VideoBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_ExtendInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_ExtendInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nAsample/src/main/java/com/javalive09/sa" +
      "mple/protoc/VideoItem.proto\022\006sample\"M\n\tV" +
      "ideoBean\022\013\n\003vid\030\001 \002(\t\022\r\n\005title\030\002 \001(\t\022\013\n\003" +
      "pic\030\003 \001(\t\022\020\n\010pay_type\030\004 \001(\005*\005\010d\020\311\001\"o\n\nEx" +
      "tendInfo\022\020\n\010subTitle\030\001 \001(\t\022\013\n\003des\030\002 \001(\t\022" +
      "\r\n\005other\030\003 \001(\t23\n\004info\022\021.sample.VideoBea" +
      "n\030d \001(\0132\022.sample.ExtendInfoB)\n\034com.javal" +
      "ive09.sample.protocB\tVideoItem"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sample_VideoBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sample_VideoBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_VideoBean_descriptor,
        new java.lang.String[] { "Vid", "Title", "Pic", "PayType", });
    internal_static_sample_ExtendInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sample_ExtendInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_ExtendInfo_descriptor,
        new java.lang.String[] { "SubTitle", "Des", "Other", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
