@startuml


package AMS #LightGray{
class ActivityManagerService {
    final ActivityStackSupervisor mStackSupervisor
}

class ActivityStackSupervisor {
    final SparseArray<ActivityDisplay> mActivityDisplays
}


class ActivityDisplay {
    final ArrayList<ActivityStack> mStacks
    DisplayWindowController mWindowContainerController
    ActivityStack createStackUnchecked()
}


class ActivityStack {
    final ArrayList<TaskRecord> mTaskHistory
    StackWindowController mWindowContainerController
    createStackWindowController()
}

class TaskRecord {
    final ArrayList<ActivityRecord> mActivities
    TaskWindowContainerController mWindowContainerController
    createWindowContainer()
    setWindowContainerController(TaskWindowContainerController controller)
}

class ActivityRecord {
    AppWindowContainerController mController
    final IApplicationToken.Stub appToken
    createWindowContainer()
}
}


package WMS #LightGray {
class WindowManagerService {
    RootWindowContainer mRoot
    public  WindowManagerService(){mRoot=new RootWindowContainer()}
    static WindowManagerService getInstance()
}
class AppWindowContainerController {
    final IApplicationToken mToken
}
class DisplayWindowController {
    WindowManagerService mService
    RootWindowContainer mRoot
}

class AppWindowToken {
    final WindowList<WindowState> mChildren
}

class TaskWindowContainerController {
    Task createTask()
}

class WindowState {

}

class StackWindowController {
    final int mStackId
}

class TaskStack {
    final WindowList<Task> mChildren
}

class DisplayContent {
    final TaskStackContainers mTaskStackContainers
    TaskStack createStack(StackWindowController controller)
}

class WindowContainer<E> {
    WindowContainerController mController
    WindowList<E> mChildren
    setController(WindowContainerController controller)
    addChild(E child, int index)
}

class Task {

}

class WindowToken {

}

class RootWindowContainer {
    final WindowList<DisplayContent> mChildren
}

class TaskStackContainers {
    final WindowList<TaskStack> mChildren
}
}

ActivityManagerService -right-> ActivityStackSupervisor
ActivityStackSupervisor *-right-> ActivityDisplay
ActivityDisplay *-right-> ActivityStack
ActivityStack *-right-> TaskRecord
TaskRecord *-right-> ActivityRecord

ActivityDisplay --> DisplayWindowController
DisplayWindowController --> RootWindowContainer
WindowManagerService -right-> RootWindowContainer
RootWindowContainer --|> WindowContainer
RootWindowContainer *-right-> DisplayContent
ActivityStack --> StackWindowController
DisplayContent -right-> TaskStackContainers
TaskStackContainers *-right-> TaskStack
TaskStackContainers --|> WindowContainer
TaskStack --|> WindowContainer
TaskStack *-right-> Task
TaskRecord --> TaskWindowContainerController
Task --|> WindowContainer
Task *-right-> AppWindowToken
ActivityRecord --> AppWindowContainerController
AppWindowContainerController --> AppWindowToken
AppWindowToken *-right-> WindowState
AppWindowToken --|> WindowToken
WindowToken --|> WindowContainer
WindowState --|> WindowContainer
StackWindowController ..> DisplayContent
TaskWindowContainerController ..> Task


@enduml