@startuml
'https://plantuml.com/sequence-diagram

autonumber

box "App" #LightYellow
participant Activity
participant ContextImpl
participant LoadedApk
participant ServiceDispatcher
participant InnerConnection
participant ActivityThread
participant Service
participant ServiceConnection
participant DeathMonitor
end box

box "Binder" #Light
participant IActivityManager
participant IApplicationThread
participant IServiceConnection
end box

box "AMS" #LightYellow
participant ActivityManagerService
participant ActiveServices
participant ConnectionRecord
end box

Activity -> Activity: bindService()
activate Activity
Activity --> ContextImpl: bindService()
activate ContextImpl
ContextImpl --> ContextImpl: bindServiceCommon()
activate ContextImpl
ContextImpl --> LoadedApk: getServiceDispatcher()
activate LoadedApk
LoadedApk --> ServiceDispatcher: new()
activate ServiceDispatcher
ServiceDispatcher --> InnerConnection: new()
activate InnerConnection
deactivate InnerConnection
deactivate ServiceDispatcher
deactivate LoadedApk



ContextImpl --> IActivityManager: bindService()
activate IActivityManager

deactivate Activity
deactivate ContextImpl
deactivate ContextImpl
deactivate IActivityManager
IActivityManager --> ActivityManagerService: bindService()
activate ActivityManagerService
ActivityManagerService --> ActiveServices: bindServiceLocked()
activate ActiveServices
ActiveServices --> ActiveServices: retrieveServiceLocked()
activate ActiveServices
deactivate ActiveServices
ActiveServices --> ConnectionRecord: new()
activate ConnectionRecord
deactivate ConnectionRecord
ActiveServices --> ActiveServices: bringUpServiceLocked()
activate ActiveServices

ActiveServices --> ActiveServices: requestServiceBindingsLocked()
activate ActiveServices
ActiveServices --> ActiveServices: bumpServiceExecutingLocked("bind")
activate ActiveServices
ActiveServices --> ActiveServices: scheduleServiceTimeoutLocked()
activate ActiveServices
deactivate ActiveServices
deactivate ActiveServices
note right: anr 埋雷 fg ? 20s : 200s

ActiveServices --> IApplicationThread: scheduleBindService()
activate IApplicationThread
deactivate IApplicationThread
deactivate ActiveServices
deactivate ActiveServices
deactivate ActivityManagerService
deactivate ActiveServices
IApplicationThread --> ActivityThread: handleBindService()
activate ActivityThread
ActivityThread --> Service: onBind()
activate Service
deactivate Service

ActivityThread --> IActivityManager: publishService()
activate IActivityManager
deactivate ActivityThread
deactivate IActivityManager
IActivityManager --> ActivityManagerService: publishService()
activate ActivityManagerService
ActivityManagerService --> ActiveServices: publishServiceLocked()
activate ActiveServices
ActiveServices --> IServiceConnection: connected()
activate IServiceConnection
deactivate IServiceConnection

ActiveServices --> ActiveServices: serviceDoneExecutingLocked()
activate ActiveServices
deactivate ActiveServices
deactivate ActiveServices
deactivate ActivityManagerService
note right: anr 拆雷

IServiceConnection --> InnerConnection: connected()
activate InnerConnection
InnerConnection --> ServiceDispatcher: connected()
activate ServiceDispatcher
ServiceDispatcher --> ServiceDispatcher: doConnected()
activate ServiceDispatcher
ServiceDispatcher --> ServiceConnection: onServiceConnected()
activate ServiceConnection
deactivate ServiceConnection
ServiceDispatcher --> DeathMonitor: new()
activate DeathMonitor
deactivate DeathMonitor
deactivate ServiceDispatcher
deactivate ServiceDispatcher
deactivate InnerConnection

DeathMonitor --> DeathMonitor: binderDied()
activate DeathMonitor
DeathMonitor --> ServiceDispatcher: death()
activate ServiceDispatcher
ServiceDispatcher --> ServiceDispatcher: doDeath()
activate ServiceDispatcher
ServiceDispatcher --> ServiceConnection: onServiceDisconnected()
activate ServiceConnection
deactivate ServiceConnection
deactivate ServiceDispatcher
deactivate ServiceDispatcher
deactivate DeathMonitor

@enduml