@startuml
skinparam BoxPadding 2
skinparam sequence {
ArrowColor black
LifeLineBorderColor black
ParticipantBorderColor black
ParticipantBackgroundColor white
}
ActivityManagerService -> ActivityManagerService: getTaskSnapshot
activate ActivityManagerService
ActivityManagerService -> TaskRecord:getSnapshot()
activate TaskRecord
TaskRecord -> WindowManagerService:getTaskSnapshot()
activate WindowManagerService
WindowManagerService -> TaskSnapshotController:getTaskSnapshot()
activate TaskSnapshotController

TaskSnapshotController -> TaskSnapShotControllerPlugs:getTaskSnapshot()
activate TaskSnapShotControllerPlugs
note right:此处为动态获取截屏插入点
TaskSnapShotControllerPlugs -> TaskSnapShotController:snapshotTasks()
activate TaskSnapShotController
deactivate TaskSnapShotController
deactivate TaskSnapShotControllerPlugs

TaskSnapshotController -> TaskSnapshotCache:getTaskSnapshot()
activate TaskSnapshotCache

TaskSnapshotCache -> TaskSnapshotCache:mRunningCache.get()
activate TaskSnapshotCache
deactivate TaskSnapshotCache
TaskSnapshotCache -> TaskSnapshotCache:tryRestoreFromDisk()
activate TaskSnapshotCache
TaskSnapshotCache -> TaskSnapshotLoader:loadTask()
activate TaskSnapshotLoader
TaskSnapshotLoader -> TaskSnapshotPersister:getProtoFile()
activate TaskSnapshotPersister
deactivate TaskSnapshotPersister
TaskSnapshotLoader -> TaskSnapshotPersister:getBitmapFile()
activate TaskSnapshotPersister
deactivate TaskSnapshotPersister
TaskSnapshotLoader -> TaskSnapshot:new()
activate TaskSnapshot
deactivate TaskSnapshot

deactivate TaskSnapshotCache
deactivate TaskSnapshotLoader
deactivate ActivityManagerService
deactivate TaskRecord
deactivate WindowManagerService
deactivate TaskSnapshotController
deactivate TaskSnapshotCache

@enduml