@startuml
skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
BackgroundColor<<Foo>> Black
BorderColor<<Foo>> Black
}
class WindowManagerService {
RootWindowContainer mRoot
}

class RootWindowContainer {
List<DisplayContent> mChildren
}


class NonAppWindowContainers {
List<WindowToken> mChildren
}

class AboveAppWindowContainers {
List<WindowToken> mChildren
}

class NonMagnifiableWindowContainers {
List<WindowToken> mChildren
}

class TaskStackContainers {
List<TaskStack> mChildren
}

class TaskStack {
List<Task> mChildren
}

class Task {
List<AppWindowToken> mChildren
}

class AppWindowToken {
List<WindowState> mChildren
}

class WindowContainer {
List<E> mChildren
}

class DisplayChildWindowContainer {
List<WindowContainer> mChildren
}

class WindowState {
List<WindowState> mChildren
}

class DisplayContent {
List<DisplayContent.DisplayChildWindowContainer> mChildren
NonAppWindowContainers mBelowAppWindowsContainers
TaskStackContainers mTaskStackContainers
AboveAppWindowContainers mAboveAppWindowsContainers
NonMagnifiableWindowContainers mImeWindowsContainers
}


WindowManagerService *-right-> RootWindowContainer
RootWindowContainer *-right-> DisplayContent
DisplayContent --> NonAppWindowContainers
DisplayContent --> TaskStackContainers
DisplayContent --> AboveAppWindowContainers
DisplayContent --> NonMagnifiableWindowContainers
TaskStackContainers *--> TaskStack
TaskStack *--> Task
Task *--> AppWindowToken
AppWindowToken *--> WindowState

'RootWindowContainer -|> WindowContainer
'DisplayContent -|> WindowContainer
'TaskStack -|> WindowContainer
'Task -|> WindowContainer
'WindowContainer <|- AppWindowToken
'DisplayChildWindowContainer <|- TaskStackContainers
'NonAppWindowContainers -|> DisplayChildWindowContainer
'AboveAppWindowContainers -|> NonAppWindowContainers
'NonMagnifiableWindowContainers -|> NonAppWindowContainers
DisplayChildWindowContainer -|> WindowContainer


@enduml