@startuml
'https://plantuml.com/sequence-diagram

autonumber

box "App" #Light
participant Activity
participant ContextImpl
participant ActivityThread
participant Instrumentation
participant Application
participant Service
participant ZygoteInit
participant RuntimeInit
participant MethodAndArgsCaller

end box

box "Binder" #Light
participant IActivityManager
participant IApplicationThread
end box


box "AMS" #LightYellow
participant ActivityManagerService
participant ActivityStack
participant ActiveServices
participant ConnectionRecord
participant Process
participant ZygoteProcess
end box

box "Zygote" #Light
participant ZygoteConnection
participant Zygote
end box

Activity -> Activity: startService()
activate Activity
Activity --> ContextImpl: startService()
activate ContextImpl
ContextImpl --> ContextImpl: startServiceCommon()
activate ContextImpl
ContextImpl --> IActivityManager: startService()
activate IActivityManager

deactivate Activity
deactivate ContextImpl
deactivate ContextImpl
deactivate IActivityManager
IActivityManager --> ActivityManagerService: startService()
activate ActivityManagerService
ActivityManagerService --> ActiveServices: startServiceLocked()
activate ActiveServices
ActiveServices --> ActiveServices: retrieveServiceLocked()
activate ActiveServices
deactivate ActiveServices
ActiveServices --> ActiveServices: startServiceInnerLocked()
activate ActiveServices
ActiveServices --> ActiveServices: bringUpServiceLocked()
activate ActiveServices
ActiveServices --> ActivityManagerService: startProcessLocked()
activate ActivityManagerService
ActivityManagerService --> ActivityManagerService: startProcess()
activate ActivityManagerService
ActivityManagerService --> Process: start()
activate Process
Process --> ZygoteProcess: start()
activate ZygoteProcess
ZygoteProcess --> ZygoteProcess: startViaZygote()
activate ZygoteProcess
ZygoteProcess --> ZygoteProcess: zygoteSendArgsAndGetResult()
activate ZygoteProcess
deactivate ZygoteProcess
deactivate ZygoteProcess
deactivate ZygoteProcess
deactivate Process
deactivate ActiveServices
deactivate ActiveServices
deactivate ActiveServices
deactivate ActivityManagerService
deactivate ActivityManagerService
deactivate ActivityManagerService


ZygoteProcess --> ZygoteConnection: processOneCommand()
activate ZygoteConnection
ZygoteConnection --> Zygote: forkAndSpecialize()
activate Zygote
deactivate Zygote
ZygoteConnection --> ZygoteConnection: handleChildProc()
activate ZygoteConnection
ZygoteConnection --> ZygoteInit: childZygoteInit()
activate ZygoteInit
ZygoteInit --> RuntimeInit: findStaticMain()
activate RuntimeInit
RuntimeInit --> MethodAndArgsCaller: new()
activate MethodAndArgsCaller
deactivate MethodAndArgsCaller
RuntimeInit --> MethodAndArgsCaller: run()
activate MethodAndArgsCaller
MethodAndArgsCaller --> ActivityThread: main()
activate ActivityThread
ActivityThread --> IActivityManager: attachApplication()
activate IActivityManager
deactivate ActivityManagerService
deactivate MethodAndArgsCaller
deactivate RuntimeInit
deactivate ZygoteInit
deactivate ZygoteProcess
deactivate ZygoteProcess
deactivate ZygoteProcess
deactivate Process
deactivate ActiveServices
deactivate ActiveServices
deactivate ActiveServices
deactivate ActivityManagerService
deactivate ActivityManagerService
deactivate IActivityManager
deactivate ActivityThread
deactivate ZygoteConnection
deactivate ZygoteConnection
IActivityManager --> ActivityManagerService: attachApplication()
activate ActivityManagerService
ActivityManagerService --> ActivityManagerService: attachApplicationLocked()
activate ActivityManagerService
ActivityManagerService --> IApplicationThread: bindApplication()
activate IApplicationThread
deactivate IApplicationThread
deactivate ActivityManagerService
IApplicationThread --> ActivityThread: handleBindApplication()
activate ActivityThread
ActivityThread --> ContextImpl: createAppContext()
activate ContextImpl
deactivate ContextImpl
ActivityThread --> Instrumentation: newApplication()
activate Instrumentation
deactivate Instrumentation
ActivityThread --> Instrumentation: callApplicationOnCreate()
activate Instrumentation
Instrumentation --> Application: onCreate()
activate Application
deactivate Application
deactivate Instrumentation
deactivate ActivityThread

ActivityManagerService --> ActiveServices: attachApplicationLocked()
activate ActiveServices
ActiveServices --> ActiveServices: realStartServiceLocked()
activate ActiveServices
ActiveServices --> ActiveServices: bumpServiceExecutingLocked("create")
activate ActiveServices
ActiveServices --> ActiveServices: scheduleServiceTimeoutLocked()
activate ActiveServices
deactivate ActiveServices
note right: anr 埋雷 fg ? 20s : 200s
ActiveServices --> IApplicationThread: scheduleCreateService()
activate IApplicationThread
deactivate IApplicationThread
deactivate ActiveServices
IApplicationThread --> ActivityThread: handleCreateService()
activate ActivityThread
ActivityThread --> Service: new()
activate Service
deactivate Service
ActivityThread --> ContextImpl: createAppContext()
activate ContextImpl
deactivate ContextImpl
ActivityThread --> ContextImpl: setOuterContext(service)
activate ContextImpl
deactivate ContextImpl
ActivityThread --> Service: attach()
activate Service
deactivate Service
ActivityThread --> Service: onCreate()
activate Service
deactivate Service
ActivityThread --> IActivityManager: serviceDoneExecuting()
activate IActivityManager
deactivate IActivityManager
deactivate ActivityThread
IActivityManager --> ActivityManagerService: serviceDoneExecuting()
activate ActivityManagerService
ActivityManagerService --> ActiveServices: serviceDoneExecutingLocked()
activate ActiveServices
deactivate ActiveServices
deactivate ActivityManagerService
note right: anr拆雷

ActiveServices --> ActiveServices: sendServiceArgsLocked()
activate ActiveServices

ActiveServices --> IApplicationThread: scheduleServiceArgs()
activate IApplicationThread
deactivate IApplicationThread
deactivate ActivityManagerService
deactivate ActiveServices
deactivate ActiveServices
deactivate ActiveServices

IApplicationThread --> ActivityThread: handleServiceArgs()
activate ActivityThread
ActivityThread --> Service: onStartCommand()
activate Service
deactivate Service
ActivityThread --> IActivityManager: serviceDoneExecuting()
activate IActivityManager
deactivate IActivityManager

IActivityManager --> ActivityManagerService: serviceDoneExecuting()
activate ActivityManagerService
deactivate IActivityManager
ActivityManagerService --> ActiveServices: serviceDoneExecutingLocked()
activate ActiveServices


@enduml